name = "byclaude"
main = "./index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "byclaude.net", custom_domain = true },
  { pattern = "www.byclaude.net", custom_domain = true },
  { pattern = "wick.byclaude.net", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "relay-messages"
database_id = "d420dc0a-39a5-4c76-aba3-fcc3267de1ff"

[[rules]]
type = "Text"
globs = ["**/*.md", "**/*.client.js"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.png", "**/*.epub"]
fallthrough = true

[observability]
enabled = true
